name: Java CI with Maven

on:
  push:
    branches:
      - main  # Ganti dengan nama branch yang sesuai jika perlu
  pull_request:
    branches:
      - main  # Ganti dengan nama branch yang sesuai jika perlu

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Ganti dengan versi Java yang sesuai
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test -X
